import { ContactLists } from './contact-list';

export const ContactList: ContactLists[] = [
    {
        Id: 1,
        Imagepath: 'assets/images/users/2.jpg',
        Name: 'Emma Adams',
        Tags: 'Friend',
        Jobtitle: 'Web Developer',
        Company: 'Wrappixel',
        Email: 'adams@mail.com',
        Phonenumber: 1548462031,
        Address: 'Boston, USA',
        DOB: new Date,
        Description: 'Felis bibendum ut tristique et egestas quis. In cursus turpis massa tincidunt dui ut.'
    },
    {
        Id: 2,
        Imagepath: 'assets/images/users/3.jpg',
        Name: 'Olivia Allen',
        Tags: 'Family',
        Jobtitle: 'Ethical Hacker',
        Company: 'Infosys',
        Email: 'allen@mail.com',
        Phonenumber: 9478021640,
        Address: 'Sydney, Australia',
        DOB: new Date,
        Description: 'Est ante in nibh mauris cursus mattis molestie a iaculis.'
    },
    {
        Id: 3,
        Imagepath: 'assets/images/users/4.jpg',
        Name: 'Emily Atkinson',
        Tags: 'Friend',
        Jobtitle: 'UX/UI Designer',
        Company: 'Google',
        Email: 'atkinson@mail.com',
        Phonenumber: 6302154203,
        Address: 'Edinburgh, UK',
        DOB: new Date,
        Description: 'Orci nulla pellentesque dignissim enim.'
    },
    {
        Id: 4,
        Imagepath: 'assets/images/users/5.jpg',
        Name: 'Isabella Anderson',
        Tags: 'Friend',
        Jobtitle: 'UX/UI Designer',
        Company: 'Tesala',
        Email: 'anderson@mail.com',
        Phonenumber: 1503201502,
        Address: 'Miami, USA',
        DOB: new Date,
        Description: 'Gravida cum sociis natoque penatibus et magnis dis parturient.'
    },
    {
        Id: 5,
        Imagepath: 'assets/images/users/6.jpg',
        Name: 'Amelia Armstrong',
        Tags: 'Office',
        Jobtitle: 'Ethical Hacker',
        Company: 'Infosys',
        Email: 'armstrong@mail.com',
        Phonenumber: 8124502316,
        Address: 'Tokyo, Japan',
        DOB: new Date,
        Description: 'Sit amet luctus venenatis lectus magna fringilla urna porttitor.'
    },
    {
        Id: 6,
        Imagepath: 'assets/images/users/7.jpg',
        Name: 'Sofia Bailey',
        Tags: 'Family',
        Jobtitle: 'Theme Designer',
        Company: 'Google',
        Email: 'bailey@mail.com',
        Phonenumber: 7080642130,
        Address: 'New York, USA',
        DOB: new Date,
        Description: 'Sapien et ligula ullamcorper malesuada proin libero nunc.'
    },
    {
        Id: 7,
        Imagepath: 'assets/images/users/8.jpg',
        Name: 'Victoria Sharma',
        Tags: 'Friend',
        Jobtitle: 'Project Manager',
        Company: 'Wrappixel',
        Email: 'sharma@mail.com',
        Phonenumber: 9040263102,
        Address: 'Miami, USA',
        DOB: new Date,
        Description: 'Id venenatis a condimentum vitae sapien pellentesque habitant morbi.'
    },
    {
        Id: 8,
        Imagepath: 'assets/images/users/agent.jpg',
        Name: 'Olivia Allen',
        Tags: 'Friend',
        Jobtitle: 'Ethical Hacker',
        Company: 'Infosys',
        Email: 'allen@mail.com',
        Phonenumber: 7800245169,
        Address: 'Sydney, Australia',
        DOB: new Date,
        Description: 'Elit at imperdiet dui accumsan sit amet nulla facilisi morbi. Porta lorem mollis aliquam ut porttitor leo a diam.'
    },
    {
        Id: 9,
        Imagepath: 'assets/images/users/agent2.jpg',
        Name: 'Emily Atkinson',
        Tags: 'Office',
        Jobtitle: 'UX/UI Designer',
        Company: 'Google',
        Email: 'atkinson@mail.com',
        Phonenumber: 9874560213,
        Address: 'Edinburgh, UK',
        DOB: new Date,
        Description: 'Vivamus arcu felis bibendum ut tristique.'
    },
    {
        Id: 10,
        Imagepath: 'assets/images/users/d2.jpg',
        Name: 'Emma Adams',
        Tags: 'Office',
        Jobtitle: 'Web Developer',
        Company: 'Wrappixel',
        Email: 'adams@mail.com',
        Phonenumber: 4500231620,
        Address: 'Boston, USA',
        DOB: new Date,
        Description: 'Habitasse platea dictumst vestibulum rhoncus.'
    },
    {
        Id: 11,
        Imagepath: 'assets/images/users/3.jpg',
        Name: 'Olivia Allen',
        Tags: 'Friend',
        Jobtitle: 'Ethical Hacker',
        Company: 'Infosys',
        Email: 'allen@mail.com',
        Phonenumber: 9748020130,
        Address: 'Sydney, Australia',
        DOB: new Date,
        Description: 'Aliquet porttitor lacus luctus accumsan tortor posuere.'
    },
    {
        Id: 12,
        Imagepath: 'assets/images/users/4.jpg',
        Name: 'Emily Atkinson',
        Tags: 'Friend',
        Jobtitle: 'UX/UI Designer',
        Company: 'Google',
        Email: 'atkinson@mail.com',
        Phonenumber: 8200154212,
        Address: 'Edinburgh, UK',
        DOB: new Date,
        Description: 'Elit at imperdiet dui accumsan sit amet nulla.'
    },

];
